//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAIL
    {
        public int OrderID { get; set; }
        public int CakeID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual CAKE CAKE { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
