//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace We_Split
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBERCOST
    {
        public int CostID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> TripID { get; set; }
        public string CostName { get; set; }
        public Nullable<int> Cost { get; set; }
    
        public virtual MEMBER MEMBER { get; set; }
        public virtual TRIP TRIP { get; set; }
    }
}
