//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace We_Split
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBERSPERTRIP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBERSPERTRIP()
        {
            this.MEMBERCOSTs = new HashSet<MEMBERCOST>();
        }
    
        public int TripID { get; set; }
        public int MemberID { get; set; }
    
        public virtual MEMBER MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEMBERCOST> MEMBERCOSTs { get; set; }
        public virtual TRIP TRIP { get; set; }
    }
}
