//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace We_Split
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WP_Project2_WeSplitEntities : DbContext
    {
        public WP_Project2_WeSplitEntities()
            : base("name=WP_Project2_WeSplitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INTERESTING_INFO> INTERESTING_INFO { get; set; }
        public virtual DbSet<LOCATION> LOCATIONs { get; set; }
        public virtual DbSet<MEMBER> MEMBERs { get; set; }
        public virtual DbSet<MEMBERCOST> MEMBERCOSTs { get; set; }
        public virtual DbSet<MEMBERSPERTRIP> MEMBERSPERTRIPs { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<TRIP> TRIPs { get; set; }
        public virtual DbSet<TRIPIMAGE> TRIPIMAGES { get; set; }
    }
}
